# Generated by Django 4.2.12 on 2025-04-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_dog_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание породы'),
        ),
        migrations.AddField(
            model_name='breed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='breed_images/', verbose_name='Изображение породы'),
        ),
    ]
